budo_api:
    resource: "@BudoApiBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

api:
    resource: '.'
    type:     'api_platform'
    prefix:   '/api'